### ISSUE TITLE
Redevelopment

### ISSUE THREAD

**Issue by izzuzantyaf** [izzuzantyaf/presisi#14]
### List fitur
- [x] Register
- [x]  Login
- [x] Update nama
- [ ]  Lupa password
- [x] Tes
- [x] Lihat hasil
- [x] History tes
- [x] Hapus history test

<hr/>

### Todo
- [x] create and replace favicon
- [ ] add description/explanation in learning type and learning recommendations
- [ ] add pictures to each learning recommendation

<hr/>

#### User
- id int PK
- name varchar(200)
- email varchar(320)
- password varchar(60)

#### Question
- id int PK
- question varchar(1000)

#### Answer choice
- id int PK
- question_id FK
- answer varchar(1000)
- expert_cf float

#### Attempt
- id int PK
- user_id FK

#### Answer
- id int PK
- user_id FK
- attempt_id FK
- answer_choice_id FK
- user_cf float

#### Learning style
- id varchar(100) PK
- name varchar(100)

#### How to learn recommendation
- id int PK
- learning_style_id FK
- name varchar(100)
